Repository dream11/kong-host-interpolate-by-header, pull requests merged in 2021-05, with the labels that each got.

#22 Add codeowners and templates
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: git and ci

#30 Add release drafter template
  .github/release-drafter.yml
Labels: ci, skip-changelog

#31 Add release automation workflows
  .ci/scripts/bump-rockspec.sh
  .ci/scripts/install-deps.sh
  .ci/scripts/upload.sh
  .github/workflows/draft-and-bump.yml
  .github/workflows/release.yml
Labels: ci

#32 Change release-drafter icons
  .ci/scripts/bump-rockspec.sh
  .ci/scripts/upload.sh
  .github/release-drafter.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: ci, skip-changelog

#33 Fix Luarocks key
  .ci/scripts/upload.sh
  .github/workflows/release.yml
Labels: ci, skip-changelog

#34 Remove log for version
  .ci/scripts/install-deps.sh
Labels: ci, publish, skip-changelog
