Repository dream11/kong-host-interpolate-by-header, pull requests merged in 2021-06, with the labels that each got.

#41 Add commit access token of dream11botpub
  .ci/scripts/bump-rockspec.sh
  .github/workflows/draft-and-bump.yml
Labels: ci

#42 Add git user to push
  .ci/scripts/bump-rockspec.sh
Labels: ci, publish

#43 Change git user to dream11botpub
  .ci/scripts/bump-rockspec.sh
Labels: ci, publish

#44 Fix bot email
  .ci/scripts/bump-rockspec.sh
Labels: ci, publish

#45 ci: fix bot email
  .ci/scripts/bump-rockspec.sh
Labels: ci, fix, publish

#46 Checkout branch with token
  .ci/scripts/bump-rockspec.sh
  .github/workflows/draft-and-bump.yml
Labels: ci, publish

#48 feature: interpolate env variables also
  .gitignore
  .pongo/pongo-setup.sh
  README.md
  docs/index.md
  kong/plugins/host-interpolate-by-header/handler.lua
  kong/plugins/host-interpolate-by-header/schema.lua
Labels: docs, feature, publish
